export { default as MySql } from "../assets/img/techs/mysql-logo.svg";
export { default as Postgres } from "../assets/img/techs/postgresql-logo.svg";
export { default as Eclipse } from "../assets/img/techs/eclipse-logo.svg";
export { default as VSCode } from "../assets/img/techs/visual-studio-logo.svg";
export { default as Java } from "../assets/img/techs/java-logo.svg";
export { default as JavaScript } from "../assets/img/techs/javascript-logo.svg";
export { default as Spring } from "../assets/img/techs/spring-logo.svg";
export { default as ReactJS } from "../assets/img/techs/react-logo.svg";
export { default as Heroku } from "../assets/img/techs/heroku-logo.svg";
export { default as HTML } from "../assets/img/techs/html-logo.svg";
export { default as CSS } from "../assets/img/techs/css3-logo.svg";
export { default as Github } from "../assets/img/techs/github-logo.svg";
export { default as MongoDB } from "../assets/img/techs/mongodb-logo.svg";
export { default as Kubernetes } from "../assets/img/techs/kubernetes-logo.svg";
export { default as Docker } from "../assets/img/techs/docker-logo.svg";
export { default as AWS } from "../assets/img/techs/aws-logo.svg";
export { default as LightOn } from "../assets/img/icons/theme-dark.svg";
export { default as LightOff } from "../assets/img/icons/theme-light.svg";
export { default as Softgraf } from "../assets/img/courses/softgraf-logo.svg"
export { default as Alura } from "../assets/img/courses/alura-logo.svg"
